language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

before_script:
  - sh -c "composer install --dev --no-progress"

script: vendor/bin/phpunit --no-configuration --coverage-text --whitelist=src/ tests/
